server:
  port: 8099

spring:
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: aomi_admin1@mem853.com
    password: Aa3.14159
  redis:
    host: 39.108.117.26
    port: 26379
    password: Macau2016
  datasource:
    url: jdbc:mysql://rm-wz9cx0j1qeen1opba8o.mysql.rds.aliyuncs.com:3306/catcher_dev?useUnicode=true&characterEncoding=utf8
    username: catcher_dev
    password: Aomi@2020
    hikari:
      maximum-pool-size: 2

logging:
  level:
    ml.memelau.catcher: debug


