spring:
  application:
    name: catcher-server
  profiles:
    active: dev
  mail:
    properties:
      mail:
        smtp:
          writetimeout: 10000
          starttls:
            enable: true
            required: true
          socketFactory:
            port: ${spring.mail.port}
            class: javax.net.ssl.SSLSocketFactory
          connectiontimeout: 30000
          ssl:
            trust: ${spring.mail.host}
          timeout: 20000
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  http:
    encoding:
      force: true



server:
  error:
    include-exception: true
    include-stacktrace: always

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: ml.memelau.catcher.server.model

pagehelper:
  helper-dialect: mysql
  reasonable: true

management:
  endpoints:
    web:
      exposure:
        include:
          - loggers
          - metrics
          - info
          - health
          - threaddump